### ISSUE TITLE
카카오 링크 동작 안해요.

### ISSUE THREAD

**Issue by jun-hak** [CoderSpinoza/kakao_flutter_sdk#11]
```
`      var template = LocationTemplate(
  "성남시 분당구 판교역로 235",
Content(
            "장소 공유",
            Uri.parse(
                "http://www.kakaocorp.com/images/logo/og_daumkakao_151001.png"),
            Link(
              webUrl: Uri.parse("https://developers.kakao.com"),
              mobileWebUrl: Uri.parse("https://developers.kakao.com"),
            ),
          ),
          social: Social(likeCount: 286, commentCount: 45, sharedCount: 845),
          buttons: [
            Button(
                "웹으로 보기",
                Link(
                    webUrl: Uri.parse("https://map.kakao.com/link/map/$y,$x"))),
          ],
          addressTitle: "카카오판교오피스");
      var uri = await LinkClient.instance.defaultWithTalk(template,
          serverCallbackArgs: {"lat": "$y", "lan": "$x"});
      await LinkClient.instance.launchKakaoTalk(uri);`
```

위젯에서 버튼 클릭시 위 코드가 실행되도록 했는데 동작을 하지 않아서 질문드립니다.
에러내용은
{code: -2, msg: failed to parse parameter. name=template_object, stringToParse=-, paramString=-, paramStringAlias=null}
이 발생합니다.

디버깅해보니 dio.dart에서  Http status error [400] 이 발생하고, 
![image](https://user-images.githubusercontent.com/29226480/73668869-de5a3700-46e9-11ea-8f7c-65d52d8fa3aa.png)

위 그림과 같이 메소드가 GET이면 response에  null을 넣어버리는 것 같습니다.
감사합니다.

**Comment by CoderSpinoza** [comment]
@jun-hak API 서버에서 에러 응답이 오는데요. 재현이 되는 것 같아서 제가 한번 살펴보겠습니다.

**Comment by jun-hak** [comment]
바쁘신데 감사합니다!

**Comment by CoderSpinoza** [comment]
0.4.0 버전에서 수정하였는데 한번 테스트 해보시겠어요? 0.4.0 버전은 Maintenance 부분에 문제가 있어서 web support 일부 기능을 롤백한 버전으로 곧 hotfix 0.4.1 버전이 나갈 예정이에요. 이 버전으로 우선 테스트 해보셔도 되고 0.4.1 버전을 기다리셔도 좋을 것 같아요!

**Comment by CoderSpinoza** [comment]
0.4.1 버전으로 다시 hotfix 배포하였습니다. 우선 이슈는 닫을게요. 이슈가 재현이 되면 다시 열어주시면 될 것 같습니다!

**Comment by jun-hak** [comment]
잘 동작해요. 감사합니다^^
