### ISSUE TITLE
혹시 이 플러그인으로 카카오 앱로그 분석도 가능한가요?

### ISSUE THREAD

**Issue by Feelthewind** [CoderSpinoza/kakao_flutter_sdk#12]
https://developers.kakao.com/docs/android/analytics

여기 나온 기능 중에서 캠페인을 통해 앱을 설치한 신규 사용자 수가 얼마인지 확인해야 하는데 혹시 이 플러그인으로 가능한지 궁금하네요.

**Comment by CoderSpinoza** [comment]
위 기능은 제공하고 있지 않습니다. Google Analytics 등 다른 툴을 사용하시는걸 추천드립니다. :(

**Comment by Feelthewind** [comment]
답변 감사합니다!
