### ISSUE TITLE
유저 동의 다음 단계로 나가지 않습니다.

### ISSUE THREAD

**Issue by blue-bada** [CoderSpinoza/kakao_flutter_sdk#17]
- Authenticate with Kakao Account
- User Agreemnet (skip if not necessary)
- **Get Authorization Code (via redirect)**
- Issue access token (via POST API)

https://previews.dropbox.com/p/thumb/AAsKUStQYeT6t_GAQ036QVJnG1bcCuVxEdGPY0HDmXExvY02i7VqPrtINYQOJ9UqW6tf0OtwyBefHkhPzxPRJwVtXLxr4yNUpc-V2bRM_-T5Hp5o6DzXt_ZfGBh1y-lKxrbgfxuwLXwIiJpzSuvXaEwBaF8-Hq1uSoYrFktW2hPqg3uD4MiS-pKXSZruApdwJxCHPajvpGmbt1ipLHyVRoopghNMrrArAphvIxUvDrD62jqP0CejAIy_cpEh8PNBKYoVPo6ZTadP5neIsxaTyUQL-QL21TwX30eKUa2YK90MeYGNIYiZWOmkSgZ-EIbCvu4mZ0CHQoh1zV75G9YLH9lT/p.png?fv_content=true&size_mode=5

유저 동의까지 한 후 "동의하고 계속하기" 버튼을 누르면 원래대로라면 창이 닫히고 authCode가 받아져야되는데, 창이 닫히지 않고, 창을 닫아도 다음 단계로 넘어가지 않습니다...

```Dart
void _signInWithKakao() async {
    KakaoContext.clientId = "{My Native App Key}";
    try {
      String authCode = await AuthCodeClient.instance.request();
      AccessTokenResponse token = await AuthApi.instance.issueAccessToken(authCode);
      AccessTokenStore.instance.toStore(token);
      print(token);
    } catch (e) {
      print(e);
    }
  }
```

**Comment by kaenchoi** [comment]
example/android/app/AndroidManifest.xml 확인하세요

**Comment by blue-bada** [comment]
감사합니다! 해결되었습니다!

**Comment by byeonguk-Yu** [comment]
저도 동일 증상을 겪고 있습니다만...
Manifest의 어느 부분을 참고하면 좋을까요?? ㅠㅠ

**Comment by kaenchoi** [comment]
`<activity android:name="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity"> <intent-filter android:label="flutter_web_auth"> <action android:name="android.intent.action.VIEW" /> <category android:name="android.intent.category.DEFAULT" /> <category android:name="android.intent.category.BROWSABLE" /> <data android:scheme="kakaodd4e9cb75815cbdf7d87ed721a659baf" android:host="oauth"/> </intent-filter> </activity>`

이부분 넣고 해보세요

**Comment by kaenchoi** [comment]
> 저도 동일 증상을 겪고 있습니다만...
> Manifest의 어느 부분을 참고하면 좋을까요?? ㅠㅠ

`<activity android:name="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity"> <intent-filter android:label="flutter_web_auth"> <action android:name="android.intent.action.VIEW" /> <category android:name="android.intent.category.DEFAULT" /> <category android:name="android.intent.category.BROWSABLE" /> <data android:scheme="kakaodd4e9cb75815cbdf7d87ed721a659baf" android:host="oauth"/> </intent-filter> </activity> `

이부분 넣고 해보세요

**Comment by byeonguk-Yu** [comment]
> > 저도 동일 증상을 겪고 있습니다만...
> > Manifest의 어느 부분을 참고하면 좋을까요?? ㅠㅠ
> 
> `<activity android:name="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity"> <intent-filter android:label="flutter_web_auth"> <action android:name="android.intent.action.VIEW" /> <category android:name="android.intent.category.DEFAULT" /> <category android:name="android.intent.category.BROWSABLE" /> <data android:scheme="kakaodd4e9cb75815cbdf7d87ed721a659baf" android:host="oauth"/> </intent-filter> </activity> `
> 
> 이부분 넣고 해보세요

말씀 주신대로 넣고 시도 해봤는데도 동일한 반응이 ^^;;.. 
제가 어딘가 지금 실수를 해 둔듯 하여 조금 더 수정 해 보겠습니다. 

도움 주셔서 대단히 감사드립니다!

**Comment by CoderSpinoza** [comment]
```
kakaodd4e9cb75815cbdf7d87ed721a659baf
```

저 부분에 개발자님 앱의 네이티브앱키를 kakao${native_app_key} 형식으로 넣으셨는데 그렇게 하셨나요?!

**Comment by byeonguk-Yu** [comment]
> ```
> kakaodd4e9cb75815cbdf7d87ed721a659baf
> ```
> 
> 저 부분에 개발자님 앱의 네이티브앱키를 kakao${native_app_key} 형식으로 넣으셨는데 그렇게 하셨나요?!

아하.. 저 부분이 문제였군요 ㅠㅠ 이제 화면은 넘어가지만 플러터에서 키 해시가 잘 등록이 되지 않아
error on issuing access token: {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}

이런 메시지가 출력 되네요... 요 부분은 좀 더 공부 해 보겠습니다 ㅠㅠ 도와주셔서 대단히 감사합니다!
