### ISSUE TITLE
androidExecParams 이 null 로 오고 있습니다.

### ISSUE THREAD

**Issue by lovedise** [CoderSpinoza/kakao_flutter_sdk#3]
카카오링크를 사용하고 있습니다.
링크를 카톡으로 보낸 후 아래 버튼을 클릭하면 param 이 안넘어오는거 같습니다.

```dart            
Button("앱으로 보기", Link(androidExecParams: "productId=222", iosExecParams: 'productId=222')),
```

```kotlin
if (Intent.ACTION_VIEW == action) {
      var uri = intent.data
      if (uri != null) {
        Log.d("native", "uri : $uri")
        sharedData.put("productId", uri?.getQueryParameter("productId"))
      }
 }
```
uri는 아래와 같이 출력됩니다. 뒤에 param 이 없이요.
`
kakaoaXXXXXXXXXXXXXXXXX://kakaolink
`

혹시 뭔가 빠뜨린게 있을까요?

**Comment by CoderSpinoza** [comment]
@lovedise 

https://pub.dev/packages/kakao_flutter_sdk/versions/0.3.1

Json encode 하는 키가 잘못되어 있었네요. 수정해서 0.3.1 버전으로 hotfix 배포하였습니다. 한번 테스트 해보시겠어요?

**Comment by lovedise** [comment]
@CoderSpinoza 

아직 동일현상입니다.  kakaoaXXXXXXXXXXXXXXXXX://kakaolink 뒤에 파라미터가 존재하지 않습니다.

**Comment by lovedise** [comment]
@CoderSpinoza 

앗 다시 빌드해보니 정상작동합니다.  

감사합니다^^
