### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by CoderSpinoza** [CoderSpinoza/kakao_flutter_sdk#4]
README is quite outdated in terms of usage and development guide.

- Current publish status
- SDK architecture section
- Development guide

**Comment by infinitytn** [comment]
Can u please provide sample code for this?

**Comment by CoderSpinoza** [comment]
@infinitytn 

Do you mean sample code for this SDK? Did you have a look this sample application?

 https://github.com/CoderSpinoza/kakao_flutter_sdk/tree/master/example

**Comment by CoderSpinoza** [comment]
330a8328dae374703c7600d3b732d4ab97ed576d resolves this.
